// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcTfNwF-LATUxPdE_SzeAXG936AiqyCMw',
    appId: '1:873260182162:web:0448000a55b05859ed544b',
    messagingSenderId: '873260182162',
    projectId: 'bengkelhelp-79fd2',
    authDomain: 'bengkelhelp-79fd2.firebaseapp.com',
    storageBucket: 'bengkelhelp-79fd2.firebasestorage.app',
    measurementId: 'G-MTZQJJHRGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASv_LjXOSL6i5urgWsIaGi4d0-cY2eumU',
    appId: '1:873260182162:android:96b124e7a398aa7eed544b',
    messagingSenderId: '873260182162',
    projectId: 'bengkelhelp-79fd2',
    storageBucket: 'bengkelhelp-79fd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVXWQdtsuYaMaDzgYqTUS7fEP5Qsr19UA',
    appId: '1:873260182162:ios:d39f4e3112055a89ed544b',
    messagingSenderId: '873260182162',
    projectId: 'bengkelhelp-79fd2',
    storageBucket: 'bengkelhelp-79fd2.firebasestorage.app',
    iosBundleId: 'com.example.bengkelhelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVXWQdtsuYaMaDzgYqTUS7fEP5Qsr19UA',
    appId: '1:873260182162:ios:d39f4e3112055a89ed544b',
    messagingSenderId: '873260182162',
    projectId: 'bengkelhelp-79fd2',
    storageBucket: 'bengkelhelp-79fd2.firebasestorage.app',
    iosBundleId: 'com.example.bengkelhelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0UiNWCm7XgUZlc1KoPMJDB1Z2iBeXTwg',
    appId: '1:873260182162:web:cacfb012b4e5a90fed544b',
    messagingSenderId: '873260182162',
    projectId: 'bengkelhelp-79fd2',
    authDomain: 'bengkelhelp-79fd2.firebaseapp.com',
    storageBucket: 'bengkelhelp-79fd2.firebasestorage.app',
    measurementId: 'G-6X3G2Y3PX2',
  );

}